[package]
name = "humm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.35", features = ["derive"] }
flate2 = "1.1.1"
json = "0.12.4"
nalgebra = "0.33.2"
nom = { version = "8.0.0", features = ["alloc"] }
