default: setup

stuff := """
    '0000':
       step: 0
       time: 0.0e+00
       dt:   1.0e+00
    '0001':
       step: 1
       time: 1.0e+00
       dt:   1.0e+00
"""

setup: 
    lmr prep-grid --job=grid.lua
    lmr prep-flow --job=flow.lua
    echo "   - 'Qrad'" >> lmrsim/snapshots/fluid.metadata
    echo "{{stuff}}" > lmrsim/snapshots/snapshot-times-metadata

raytrace absorptivity:
    lmr-raytrace -k={{absorptivity}}
    lmr snapshot2vtk --all

intensity absorptivity:
    lmr-intensity -k={{absorptivity}}
    lmr snapshot2vtk --all

extract:
    lmr extract-line --line-list="0,5,0,1,5,0,101" --names="Qrad" \
        | xclip -selection clipboard
    @echo "Copied results to clipboard"
